// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCore.EntityFrameworkCore.Context;

namespace NetCore.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20201019073122_v2.0")]
    partial class v20
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NetCore.EntityFrameworkCore.Models.Menu", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreateBy")
                        .HasMaxLength(32);

                    b.Property<DateTime?>("CreateTime");

                    b.Property<bool>("Hidden");

                    b.Property<string>("Icon")
                        .HasMaxLength(32);

                    b.Property<string>("MenuCode")
                        .HasMaxLength(32);

                    b.Property<string>("MenuName")
                        .HasMaxLength(32);

                    b.Property<bool>("NoChildren");

                    b.Property<int>("ParentId");

                    b.Property<string>("Path")
                        .HasMaxLength(32);

                    b.Property<int>("Sort");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(32);

                    b.Property<DateTime?>("UpdateTime");

                    b.HasKey("ID");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("NetCore.EntityFrameworkCore.Models.Role", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreateBy")
                        .HasMaxLength(32);

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(32);

                    b.Property<DateTime?>("UpdateTime");

                    b.HasKey("ID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("NetCore.EntityFrameworkCore.Models.RoleMenu", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreateBy")
                        .HasMaxLength(32);

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("MenuCode");

                    b.Property<string>("RoleCode");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(32);

                    b.Property<DateTime?>("UpdateTime");

                    b.HasKey("ID");

                    b.ToTable("RoleMenu");
                });

            modelBuilder.Entity("NetCore.EntityFrameworkCore.Models.StoreFiles", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreateBy")
                        .HasMaxLength(32);

                    b.Property<DateTime?>("CreateTime");

                    b.Property<long>("FileBytes");

                    b.Property<string>("FileCategory")
                        .HasMaxLength(16);

                    b.Property<string>("FileExt")
                        .HasMaxLength(8);

                    b.Property<string>("FileName")
                        .HasMaxLength(128);

                    b.Property<string>("FileType")
                        .HasMaxLength(64);

                    b.Property<string>("RelationFilePath")
                        .HasMaxLength(128);

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(32);

                    b.Property<DateTime?>("UpdateTime");

                    b.HasKey("ID");

                    b.ToTable("StoreFiles");
                });

            modelBuilder.Entity("NetCore.EntityFrameworkCore.Models.TaskJob", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApiUrl")
                        .HasMaxLength(256);

                    b.Property<string>("CreateBy")
                        .HasMaxLength(32);

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("CronExpression")
                        .HasMaxLength(512);

                    b.Property<string>("CronExpressionDescription")
                        .HasMaxLength(512);

                    b.Property<string>("Description")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("EndRunTime");

                    b.Property<string>("ExceptionMsg");

                    b.Property<bool>("IsDelete");

                    b.Property<int>("MailMessage");

                    b.Property<string>("RequestHead");

                    b.Property<string>("RequestParams");

                    b.Property<int>("RequestType");

                    b.Property<int>("RunCount");

                    b.Property<DateTime>("StartRunTime");

                    b.Property<string>("TaskGroup")
                        .HasMaxLength(64);

                    b.Property<string>("TaskName")
                        .HasMaxLength(64);

                    b.Property<int>("TaskState");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(32);

                    b.Property<DateTime?>("UpdateTime");

                    b.HasKey("ID");

                    b.ToTable("TaskJob");
                });

            modelBuilder.Entity("NetCore.EntityFrameworkCore.Models.TaskJobLog", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreateBy")
                        .HasMaxLength(32);

                    b.Property<DateTime?>("CreateTime");

                    b.Property<double>("ExecutionDuration");

                    b.Property<DateTime>("ExecutionTime");

                    b.Property<string>("JobName")
                        .HasMaxLength(64);

                    b.Property<string>("RunLog");

                    b.Property<Guid>("TaskJobId");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(32);

                    b.Property<DateTime?>("UpdateTime");

                    b.HasKey("ID");

                    b.ToTable("TaskJobLog");
                });

            modelBuilder.Entity("NetCore.EntityFrameworkCore.Models.Test", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreateBy")
                        .HasMaxLength(32);

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("Name");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(32);

                    b.Property<DateTime?>("UpdateTime");

                    b.HasKey("ID");

                    b.ToTable("Test");
                });

            modelBuilder.Entity("NetCore.EntityFrameworkCore.Models.UserInfo", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreateBy")
                        .HasMaxLength(32);

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int>("Gender");

                    b.Property<string>("NickName");

                    b.Property<string>("Password")
                        .HasMaxLength(64);

                    b.Property<string>("PhoneNumber");

                    b.Property<int>("State");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(32);

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<string>("UserCode");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.ToTable("UserInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
